// src/users.js
//JSON.parse(localStorage.getItem('app_users'))
export const users = [
  {
    id: 1,
    username: 'admin',
    password: 'admin123',
    name: 'Administrador',
    email: 'admin@topconstrutora.com',
    role: 'admin',
    department: 'TI',
    position: 'Diretor de TI',
    phone: '(11) 99999-9999',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-01T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 38,
    username: 'karuline',
    password: 'karuline123',
    name: 'Karuline Makiyama Silva',
    email: 'karuline.makiyama@mapah.com.br',
    role: 'analyst',
    department: 'Contabilidade',
    position: 'Assessor(a) Contábil',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-15T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 159,
    username: 'charles',
    password: 'charles123',
    name: 'Charles Silva Barcelos',
    email: 'charles.barcelos@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Administrativo de obra',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-16T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 192,
    username: 'nassar',
    password: 'nassar123',
    name: 'Nassar Tecnologia - Assessoria TI',
    email: 'suporte@nassarti.com.br',
    role: 'analyst',
    department: 'TI',
    position: 'Suporte TI (email, intranet, criação de pastas , etc)',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-17T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 131,
    username: 'silvestre',
    password: 'silvestre123',
    name: 'Silvestre Álvares de Rezende',
    email: 'silvestre.alvares@topconstrutora.com',
    role: 'analyst',
    department: 'Suprimentos',
    position: 'Analista de Suprimentos',
    phone: '62 8128-4861',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-18T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 138,
    username: 'antonio',
    password: 'antonio123',
    name: 'Antonio Fernandes Ramirez',
    email: 'antonio.ramirez@topconstrutora.com',
    role: 'manager',
    department: 'Suprimentos',
    position: 'Coordenador(a) de Suprimentos',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-19T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 107,
    username: 'erik',
    password: 'erik123',
    name: 'Erik Portilho',
    email: 'erikportilho@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-20T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 9,
    username: 'renato',
    password: 'renato123',
    name: 'Renato Ferreira Gomes',
    email: 'renato.gomes@topconstrutora.com',
    role: 'manager',
    department: 'Engenharia',
    position: 'Coordenador(a) de Engenharia',
    phone: '(62) 3922-0464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-21T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 169,
    username: 'marley',
    password: 'marley123',
    name: 'Marley Pedro Farias',
    email: 'marley.farias@topconstrutora.com',
    role: 'analyst',
    department: 'Suprimentos',
    position: 'Analista de Suprimentos',
    phone: '62 9280-4083',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-22T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 50,
    username: 'isabela',
    password: 'isabela123',
    name: 'Isabela Valério',
    email: 'isabela.valerio@topconstrutora.com',
    role: 'manager',
    department: 'Comercial',
    position: 'Coordenadora Comercial',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-23T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 28,
    username: 'rafael',
    password: 'rafael123',
    name: 'Rafael Ferreira Gomes',
    email: 'rafael@topconstrutora.com',
    role: 'admin',
    department: 'Obras',
    position: 'Diretor Técnico',
    phone: '(62) 3922-0464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-24T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 14,
    username: 'marcelo',
    password: 'marcelo123',
    name: 'Marcelo Silva Potenciano',
    email: 'marcelo.potenciano@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Supervisor Geral dos Administrativos de Obra',
    phone: '(62) 3922-0464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-25T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 73,
    username: 'jose',
    password: 'jose123',
    name: 'José Antônio Peixoto de Paiva Junior',
    email: 'jose.peixoto@topconstrutora.com',
    role: 'manager',
    department: 'Engenharia',
    position: 'Coordenador(a) de Engenharia',
    phone: '62 39220464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-26T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 81,
    username: 'luciano',
    password: 'luciano123',
    name: 'Luciano Aires da Costa',
    email: 'luciano.costa@topconstrutora.com',
    role: 'engineer',
    department: 'Engenharia',
    position: 'Engenheiro Supervisor de Orçamento',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-27T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 112,
    username: 'ricardo',
    password: 'ricardo123',
    name: 'Ricardo Alexandre Dantas',
    email: 'ricardo.dantas@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Supervisor de Segurança do Trabalho',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-28T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 91,
    username: 'luziclezio',
    password: 'luziclezio123',
    name: 'Luziclezio Rodrigues da Cruz',
    email: 'clezio.cruz@topconstrutora.com',
    role: 'analyst',
    department: 'DP/RH',
    position: 'Encarregado de Departamento Pessoal',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-29T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 115,
    username: 'everton',
    password: 'everton123',
    name: 'Everton Fernandes Freitas',
    email: 'everton.freitas@topconstrutora.com',
    role: 'manager',
    department: 'Obras',
    position: 'Coordenador(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-30T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 166,
    username: 'danuza',
    password: 'danuza123',
    name: 'Danuza Rafaela Da Silva Costa',
    email: 'rafaela.costa@topconstrutora.com',
    role: 'analyst',
    department: 'DP/RH',
    position: 'Analista de Departamento Pessoal',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-01-31T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 8,
    username: 'romas',
    password: 'romas123',
    name: 'Romas José de Oliveira Filho',
    email: 'romas@topconstrutora.com',
    role: 'admin',
    department: 'Comercial',
    position: 'Diretor de Novos Negócios',
    phone: '(62) 3922-0464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-01T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 29,
    username: 'vinicius',
    password: 'vinicius123',
    name: 'Vinicius Montrezol Honório',
    email: 'vinicius@topconstrutora.com',
    role: 'admin',
    department: 'Financeiro',
    position: 'Diretor Administrativo e Financeiro',
    phone: '(62) 3922-0464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-02T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 142,
    username: 'diony',
    password: 'diony123',
    name: 'Diony Cezar Justino da Silva',
    email: 'diony.silva@topconstrutora.com',
    role: 'analyst',
    department: 'DP/RH',
    position: 'Encarregado de Departamento Pessoal',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-03T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 185,
    username: 'lais',
    password: 'lais123',
    name: 'Lais Portela Gardini Almeida',
    email: 'lais.gardini@topconstrutora.com',
    role: 'admin',
    department: 'DP/RH',
    position: 'Supervisor(a) de RH',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-04T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 154,
    username: 'naftali',
    password: 'naftali123',
    name: 'Naftali Bispo da Silva',
    email: 'financeiro@topconstrutora.com',
    role: 'analyst',
    department: 'Financeiro',
    position: 'Analista Financeira',
    phone: '62 8130-1988',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-05T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 161,
    username: 'suzane',
    password: 'suzane123',
    name: 'Suzane Moraes Teixeira',
    email: 'suzane.moraes@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Técnico(a) de Segurança do Trabalho',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-06T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 179,
    username: 'arianne',
    password: 'arianne123',
    name: 'Arianne da Silva Milhomem Moreira',
    email: 'arianne.milhomem@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Técnico(a) de Segurança do Trabalho',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-07T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 113,
    username: 'jessica',
    password: 'jessica123',
    name: 'Jéssica Cristina Dias',
    email: 'jessica.dias@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-08T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 48,
    username: 'jeane',
    password: 'jeane123',
    name: 'Jeane Nair Gomes e Silva',
    email: 'jeane.silva@topconstrutora.com',
    role: 'engineer',
    department: 'Engenharia',
    position: 'Engenheiro(a) de Planejamento e Orçamento',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-09T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 140,
    username: 'jose',
    password: 'jose123',
    name: 'José Henrique Gomes Silva',
    email: 'jose.henrique@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-10T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 158,
    username: 'melania',
    password: 'melania123',
    name: 'Melania Thaina Souza Septimio',
    email: 'melania.souza@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-11T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 11,
    username: 'priscila',
    password: 'priscila123',
    name: 'Priscila Pereira Nunes',
    email: 'priscila.nunes@topconstrutora.com',
    role: 'manager',
    department: 'SGQ',
    position: 'Coordenador(a) Administrativo(a) /Financeiro(a)',
    phone: '(62) 3922-0464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-12T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 51,
    username: 'matheus',
    password: 'matheus123',
    name: 'Matheus Cardoso Araújo Neiva',
    email: 'matheus.cardoso@topconstrutora.com',
    role: 'analyst',
    department: 'Suprimentos',
    position: 'Analista de Suprimentos',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-13T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 70,
    username: 'ingreed',
    password: 'ingreed123',
    name: 'Ingreed Nabi Reis de Paula',
    email: 'ingreed.nabi@topconstrutora.com',
    role: 'analyst',
    department: 'SGQ',
    position: 'Engenheira de Qualidade',
    phone: '62 39220464',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-14T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 94,
    username: 'anna',
    password: 'anna123',
    name: 'Anna Beatriz Rodrigues de Souza Lima',
    email: 'anna.rodrigues@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-15T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 128,
    username: 'danillo',
    password: 'danillo123',
    name: 'Danillo Henrique Cangussú Prado',
    email: 'danillo.cangussu@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-16T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 76,
    username: 'tulio',
    password: 'tulio123',
    name: 'Túlio Rabelo Carvalho',
    email: 'tulio.carvalho@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '64 9 9645-3818',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-17T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 95,
    username: 'johnny',
    password: 'johnny123',
    name: 'Johnny Castro Oliveira',
    email: 'johnny.oliveira@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-18T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 195,
    username: 'luiz',
    password: 'luiz123',
    name: 'Luiz Fernandes Vieira Neto',
    email: 'luiz.neto@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Administrativo de Obra',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-19T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 83,
    username: 'sirleide',
    password: 'sirleide123',
    name: 'Sirleide Oliveira Araujo',
    email: 'sirleide.oliveira@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Auxiliar Técnico(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-20T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 104,
    username: 'yasmin',
    password: 'yasmin123',
    name: 'Yasmin Mendes Azevedo',
    email: 'yasmin.mendes@topconstrutora.com',
    role: 'engineer',
    department: 'Engenharia',
    position: 'Engenheiro(a) de Projeto',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-21T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 87,
    username: 'carlos',
    password: 'carlos123',
    name: 'Carlos Alberto Barbosa Freitas',
    email: 'carlos.barbosa@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Administrativo de Obra',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-22T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 108,
    username: 'marcio',
    password: 'marcio123',
    name: 'Marcio Henrique de Andrade Xavier Filho',
    email: 'marcio.filho@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-23T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 164,
    username: 'vitor',
    password: 'vitor123',
    name: 'Vitor Augusto Braz Fonseca',
    email: 'vitor.fonseca@topconstrutora.com',
    role: 'engineer',
    department: 'Novos Negócios Incorporação',
    position: 'Engenheiro de Novos Negócios',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-24T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 196,
    username: 'bruno',
    password: 'bruno123',
    name: 'Bruno Luan Silva Ramos',
    email: 'bruno.ramos@topconstrutora.com',
    role: 'engineer',
    department: 'Engenharia',
    position: 'Engenheiro de Planejamento e Controle',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-25T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 105,
    username: 'gabriel',
    password: 'gabriel123',
    name: 'Gabriel Dal Ross Peres',
    email: 'gabriel.peres@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-26T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 130,
    username: 'ariadna',
    password: 'ariadna123',
    name: 'Ariadna Crysla Ferreira Confessor',
    email: 'ariadna.ferreira@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-27T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 135,
    username: 'adrielle',
    password: 'adrielle123',
    name: 'Adrielle Leal de Jesus',
    email: 'adrielle.leal@topconstrutora.com',
    role: 'analyst',
    department: 'SGQ',
    position: 'Analista de Qualidade',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-02-28T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 177,
    username: 'raysa',
    password: 'raysa123',
    name: 'Raysa Moniza Silva Americo',
    email: 'raysa.moniza@topconstrutora.com',
    role: 'engineer',
    department: 'Obras',
    position: 'Engenheiro(a) de Obras',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-01T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 191,
    username: 'marcello',
    password: 'marcello123',
    name: 'Marcello Oliveira de Alencar',
    email: 'marcello.oliveira@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Administrativo de Obra',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-02T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 193,
    username: 'herica',
    password: 'herica123',
    name: 'Herica Ferreira de Arruda',
    email: 'herica.ferreira@topconstrutora.com',
    role: 'analyst',
    department: 'Financeiro',
    position: 'Recepção/ Auxiliar administrativo',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-03T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 148,
    username: 'isabela',
    password: 'isabela123',
    name: 'Isabela Gomes Gouveia',
    email: 'isabela.gomes@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Estagiário(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-04T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 79,
    username: 'heitor',
    password: 'heitor123',
    name: 'Heitor Custódio Gonçalves',
    email: 'heitor.goncalves@topconstrutora.com',
    role: 'analyst',
    department: 'Engenharia',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-05T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 156,
    username: 'gabriel',
    password: 'gabriel123',
    name: 'Gabriel Caetano Peres',
    email: 'gabriel.caetano@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Auxiliar Administrativo',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-06T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 82,
    username: 'larissye',
    password: 'larissye123',
    name: 'Larissye Sthefanny Alves Maciel',
    email: 'larissye.alves@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-07T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 147,
    username: 'giovana',
    password: 'giovana123',
    name: 'Giovana Aparecida Seidel',
    email: 'giovana.seidel@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Administrativo de Obra',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-08T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 181,
    username: 'andressa',
    password: 'andressa123',
    name: 'Andressa Pina de Melo',
    email: 'andressa.pina@topconstrutora.com',
    role: 'analyst',
    department: 'SGQ',
    position: 'Estagiário(a) de Qualidade',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-09T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 146,
    username: 'anna',
    password: 'anna123',
    name: 'Anna Laura Cordeiro e Castro',
    email: 'anna.cordeiro@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Auxiliar Técnico(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-10T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 168,
    username: 'gabriel',
    password: 'gabriel123',
    name: 'Gabriel Damasceno Menezes Faquim',
    email: 'gabriel.faquim@topconstrutora.com',
    role: 'analyst',
    department: 'Planejamento',
    position: 'Estagiário(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-11T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 178,
    username: 'hafsah',
    password: 'hafsah123',
    name: 'Hafsah Alves Pereira e Silva',
    email: 'hafsah.silva@topconstrutora.com',
    role: 'analyst',
    department: 'Engenharia',
    position: 'Estagiário(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-12T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 110,
    username: 'debora',
    password: 'debora123',
    name: 'Débora Alves Garcia',
    email: 'debora.alves@topcontrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Assistente de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-13T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 194,
    username: 'ana',
    password: 'ana123',
    name: 'Ana Luiza Silva',
    email: 'ana.silva@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Técnico(a) de Segurança do Trabalho',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-14T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 111,
    username: 'ana',
    password: 'ana123',
    name: 'Ana Luísa Lacerda Paranhos',
    email: 'ana.paranhos@topconstrutora.com',
    role: 'analyst',
    department: 'Engenharia',
    position: 'Estagiário(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-15T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 184,
    username: 'andressa',
    password: 'andressa123',
    name: 'Andressa Eliza Oliveira do Carmo',
    email: 'andressa.oliveira@topconstrutora.com',
    role: 'analyst',
    department: 'Obras',
    position: 'Estagiário(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-16T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 186,
    username: 'davi',
    password: 'davi123',
    name: 'Davi Valerio de Oliveira',
    email: 'davi.valerio@topconstrutora.com',
    role: 'analyst',
    department: 'Inovação e Tecnologia',
    position: 'Estagiário(a) de Inovação e Tecnologia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-17T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 157,
    username: 'joao',
    password: 'joao123',
    name: 'João Henrique Corrêa de Araújo Tomaz',
    email: 'joao.tomaz@topconstrutora.com',
    role: 'analyst',
    department: 'Engenharia',
    position: 'Estagiário(a) de Engenharia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-18T00:00:00.000Z',
    lastLogin: null
  },
  {
    id: 18328429,
    username: 'davizada',
    password: 'davi123',
    name: 'Davi Valerio de Oliveira',
    email: 'davivaleriol@gmail.com',
    role: 'analyst',
    department: 'Inovação e Tecnologia',
    position: 'Estagiário(a) de Inovação e Tecnologia',
    phone: '',
    avatarUrl: '/api/placeholder/80/80',
    createdAt: '2023-03-17T00:00:00.000Z',
    lastLogin: null
  },
];

// Definições de roles e suas permissões
export const roles = {
  admin: {
    name: 'Administrador',
    permissions: ['all']
  },
  manager: {
    name: 'Gerente',
    permissions: ['view_reports', 'manage_users', 'manage_projects']
  },
  engineer: {
    name: 'Engenheiro',
    permissions: ['view_projects', 'update_projects']
  },
  analyst: {
    name: 'Analista',
    permissions: ['view_reports']
  }
};